{
  lib,
  config,
  pkgs,
  ...
}:

# What SMF needs at *runtime*, as opposed to what it needs to be packaged.
#
# ../boot/illumos-init.nix puts `svc.startd` in /etc/inittab and symlinks the
# two daemons into /lib/svc/bin. That is enough for init to try, and not
# nearly enough for startd to succeed, because three things it takes for
# granted are absent here:
#
#   * **A writable repository.** svc.configd opens `/etc/svc/repository.db`
#     (REPOSITORY_DB, lib/libscf/inc/libscf_priv.h:301) with a hard-coded
#     path, and startd exec's it with *no arguments at all*
#     (cmd/svc/startd/fork.c:485), so there is no knob to turn. The root is
#     read-only hsfs, and sqlite needs to write the database, its journal and
#     its temporaries. The one writable filesystem that exists this early is
#     /etc/svc/volatile, a tmpfs the *kernel* mounts in vfs_mountdevices()
#     (uts/common/fs/vfs.c:936) -- so `/lib/svc/bin/svc.configd` is pointed at
#     a wrapper that passes `-r` naming a repository over there. configd
#     already puts everything else (the door, the nonpersistent database, the
#     sqlite temp directory) in /etc/svc/volatile, so this makes the whole
#     repository live in one place.
#
#   * **A repository with something in it.** configd creates an empty, valid,
#     *serviceless* repository when the file is absent
#     (backend.c:1873 -> BACKEND_CREATE_NEED_INIT -> backend_init_schema), and
#     startd survives that -- libscf_populate_graph() over an empty scope is
#     zero iterations, not an error. But `can_come_up()` is then false, and
#     graph_thread() responds by spawning sulogin_thread (graph.c:6193), which
#     forks /sbin/sulogin on /dev/console forever. Neither exists. So the
#     repository has to be populated *before* startd starts, which is what
#     `svccfg import` under SVCCFG_REPOSITORY does below: that variable makes
#     svccfg fork a private svc.configd against a named database
#     (svccfg_engine.c:488), which is the only way to write a repository with
#     no restarter running.
#
#   * **Sockets.** sockfs keeps no built-in family/type/protocol table --
#     sockparams_init() (uts/common/fs/sockfs/sockparams.c:87) creates an
#     empty list -- so until soconfig(8) has issued the `sockconfig` syscall
#     every socket(2) returns EPROTONOSUPPORT, unix-domain included. On a real
#     system /lib/svc/method/devices-local runs `soconfig -d /etc/sock2path.d`;
#     here it has to happen before startd, because nothing is running that
#     could run a method yet.
#
# Everything is therefore funnelled through one script that init runs in
# startd's place: it makes the writable tree, configures sockets, imports the
# manifests and then exec's startd.

let
  inherit (lib)
    mkIf
    mkOption
    types
    optionalString
    ;

  isIllumos = config.nixpkgs.hostPlatform.isSunOS;
  cfg = config.boot.illumos.smf;

  startd = pkgs.illumos.svc-startd or null;
  configd = pkgs.illumos.svc-configd or null;
  svccfg = pkgs.illumos.svccfg or null;
  soconfig = pkgs.illumos.soconfig or null;
  mountUfs = pkgs.illumos.mount-ufs or null;
  ifconfig = pkgs.illumos.ifconfig or null;
  dlmgmtd = pkgs.illumos.dlmgmtd or null;
  ipmgmtd = pkgs.illumos.ipmgmtd or null;

  # Whether to try to get a writable root. Only meaningful for a UFS root --
  # hsfs cannot be written at all -- and only possible once mount(8) for ufs is
  # packaged, hence the `or null` above.
  remountRoot = config.boot.illumos.rootfs or "hsfs" == "ufs" && mountUfs != null;

  # Spelled `or null` throughout, and gated on all four: this module has to
  # stay evaluable against a nixpkgs that has not packaged them yet. See the
  # same reasoning in illumos-init.nix.
  available =
    startd != null
    && configd != null
    && svccfg != null
    && soconfig != null
    && ifconfig != null
    && dlmgmtd != null
    && ipmgmtd != null;

  volatile = "/etc/svc/volatile";
  repository = "${volatile}/repository.db";

  manifestDir = config.system.build.smfManifests or null;

  shell = "${pkgs.bash}/bin/bash";

  # startd exec's CONFIGD_PATH with an empty argv (fork.c:485), so the only
  # place to add `-r` is the file that path names. A `#!` script works because
  # exec/intpexec is in the kernel's module list.
  configdWrapper = pkgs.writeScript "svc.configd-wrapper" ''
    #!${shell}
    exec ${configd}/lib/svc/bin/svc.configd -r ${repository} "$@"
  '';

  bootstrap = pkgs.writeScript "smf-bootstrap" ''
    #!${shell}
    # Generated by nixbsd. Runs as init's `sysinit` entry, in place of
    # svc.startd, and exec's svc.startd at the end.

    ${optionalString (cfg.consoleDevice != null) ''
      # There is no /dev/console: devfsadm(8) creates it and is not packaged.
      # Write to the device node instead, so that a failure here is visible
      # rather than silent. Deliberately not `set -e`: every step below is
      # best-effort, and losing the console must not stop the boot.
      #
      # Note there is no `</dev/null` here, and there must not be: /dev/null
      # does not exist either, and a shell reports a failed *redirection* by
      # failing the whole command, so adding it would silently cost the log.
      exec >>${cfg.consoleDevice} 2>&1 || :
    ''}
    set -x

    # init hands its children a minimal environment (see /etc/default/init,
    # which definit(3) reads for TZ and CMASK and nothing else), so name the
    # utilities' directory rather than trusting a default PATH.
    PATH=${pkgs.coreutils}/bin:${pkgs.bash}/bin
    export PATH

    ${optionalString remountRoot ''
      # Get a writable root.
      #
      # The kernel always mounts the root read-only -- ufs_mountroot() sets
      # VFS_RDONLY for ROOT_INIT (uts/common/fs/ufs/ufs_vfsops.c) -- and
      # illumos reaches a writable one through a second, ROOT_REMOUNT pass.
      # Upstream drives that from svc:/system/filesystem/root, whose method
      # script wants a good deal more of userland than is packaged here, so do
      # just the remount and do it before anything wants to write.
      #
      # The fstype-specific mount is invoked directly rather than through the
      # generic /usr/sbin/mount, which is not packaged. That means supplying
      # both operands: cmd/fs.d/ufs/mount/mount.c:226 insists on exactly two
      # (`(argc - optind) != 2` is a usage error), because resolving one from
      # the other is the dispatcher's job, not this program's. Its usage text
      # saying `{special | mount_point}` describes the dispatcher, not itself.
      #
      # The special is read out of /etc/mnttab rather than written down here.
      # It is /ramdisk:a today, but that is a consequence of the root being a
      # multiboot module, and it stops being true the moment the root moves to
      # a real disk. mnttab is the kernel's own answer to the question.
      #
      # Pure shell, no awk: this script's PATH is coreutils and bash only.
      root_special=
      while read -r special mountp rest; do
        if [ "$mountp" = "/" ]; then
          root_special=$special
          break
        fi
      done < /etc/mnttab

      # What mnttab reports is not always a path that can be opened. For a
      # ramdisk root it is the boot-time name the kernel used:
      #
      #     /ramdisk:a      /       ufs     dev=600001      0
      #
      # while the block device node actually lives at /devices/ramdisk:a --
      # note *not* under /devices/pseudo/, which is where the ramdisk@1024
      # directory sits and where it is natural to go looking. mount(8) needs
      # the node, and fails with "no such file or directory" given the name.
      #
      # A disk root does report an openable path (/dev/dsk/...), so prefer the
      # name as given and only fall back to prefixing /devices.
      if [ -n "$root_special" ] && [ ! -e "$root_special" ] \
         && [ -e "/devices$root_special" ]; then
        root_special=/devices$root_special
      fi

      # Best-effort, like everything else in this script: if any of this fails
      # the boot continues with a read-only root, which is what it did before,
      # and the `set -x` trace says so.
      if [ -n "$root_special" ]; then
        ${mountUfs}/lib/fs/ufs/mount -o remount,rw "$root_special" /
      else
        echo "smf-bootstrap: no root entry in /etc/mnttab; not remounting"
      fi

      # `set -x` shows the command but not whether it achieved anything, and
      # the distinction matters to everything below: with a read-only root the
      # /etc/svc/volatile redirections are load-bearing, and without one they
      # are not.
      if touch /.rw-probe 2>/dev/null; then
        rm -f /.rw-probe
        echo "smf-bootstrap: root is writable"
      else
        echo "smf-bootstrap: root is READ-ONLY; the remount above did not take"
      fi
    ''}

    # The writable tree. /etc/svc/volatile is a kernel-mounted tmpfs; each of
    # these is the target of a symlink baked into the read-only root.
    mkdir -p ${volatile}/svc-log ${volatile}/var-run ${volatile}/var-adm \
             ${volatile}/var-log ${volatile}/nix-var/nix ${volatile}/tmp
    chmod 1777 ${volatile}/tmp

    # Without this every socket(2) fails, whatever the family.
    ${soconfig}/bin/soconfig -d /etc/sock2path.d

    # A repository with no services in it makes startd go straight to
    # sulogin, so populate it here rather than leaving it to
    # manifest-import.
    #
    # SVCCFG_CONFIGD_PATH names the *real* binary rather than letting svccfg
    # fall back to /lib/svc/bin/svc.configd, which is the wrapper above:
    # svccfg passes its own `-r`, and going through the wrapper would mean two
    # of them on one command line.
    #
    # The files are named, rather than the directory: `smf.manifests` lays
    # them out by service name, so they sit one and two levels down
    # (site/nix-daemon.xml, milestone/single-user.xml), and svccfg's directory
    # walk is not recursive.
    if [ ! -f ${repository} ]; then
      shopt -s nullglob
      # Three levels, not two: FMRIs nest as deeply as their name does, so
      # `svc:/system/filesystem/local` lands at
      # manifest/system/filesystem/local.xml. A two-level glob silently misses
      # those, and the only symptom is the services that depend on them sitting
      # offline forever with "Dependency ... is absent".
      manifests=(
        /lib/svc/manifest/*.xml
        /lib/svc/manifest/*/*.xml
        /lib/svc/manifest/*/*/*.xml
      )
      SVCCFG_REPOSITORY=${repository} \
      SVCCFG_CONFIGD_PATH=${configd}/lib/svc/bin/svc.configd \
      SVCCFG_DOOR_PATH=${volatile} \
        ${svccfg}/bin/svccfg import "''${manifests[@]}"
    fi

    exec /lib/svc/bin/svc.startd
  '';
  # svc:/network/datalink-management's start method.
  #
  # This is the service whose absence made the NIC look like a kernel problem
  # for a long time. The device is enumerated and attached -- `/devices/pci@0,0`
  # holds `pci1af4,1@3:vioif0`, the minor node and all -- and yet
  #
  #     ifconfig: cannot plumb vioif0: Interface does not exist
  #     vioif0: DL_ATTACH_REQ failed: DL_BADPPA
  #
  # because libdladm does not read datalink state from the kernel. It asks
  # dlmgmtd over a door opened on demand in `dladm_door_fd()`
  # (lib/libdladm/common/libdladm.c), and with no daemon there is no door, so
  # the name lookup fails before anything touches the hardware. ifconfig
  # reaches the same code through libipadm, so `ifconfig -a` is equally blind
  # -- which is why the symptom reads as "there is no NIC" rather than "there
  # is no daemon". nixpkgs' dlmgmtd.nix says all of this in its header; it was
  # packaged and then never started.
  #
  # dlmgmtd forks and lets its parent exit, so this is a `contract` service and
  # the method simply runs it, exactly as upstream's svc-dlmgmtd does. That
  # script is shipped in the package but is not used here: it sources
  # /lib/svc/share/smf_include.sh and calls smf_is_nonglobalzone, neither of
  # which is packaged.
  dlScript = pkgs.writeScript "smf-dlmgmtd" ''
    #!${shell}
    # Generated by nixbsd for svc:/network/datalink-management.
    set -x

    # dlmgmtd requires /etc/dladm/datalink.conf to exist *and to be writable*
    # -- it rewrites the file as links come and go -- so the seed copy from
    # the package is copied into the volatile tree rather than symlinked out
    # of the store. /etc/dladm is a symlink to that directory (see below).
    ${pkgs.coreutils}/bin/mkdir -p ${volatile}/dladm
    if [ ! -f ${volatile}/dladm/datalink.conf ]; then
      ${pkgs.coreutils}/bin/cp \
        ${dlmgmtd}/share/dlmgmtd/datalink.conf \
        ${volatile}/dladm/datalink.conf
      ${pkgs.coreutils}/bin/chmod 644 ${volatile}/dladm/datalink.conf
    fi

    exec ${dlmgmtd}/sbin/dlmgmtd
  '';

  # svc:/network/ip-interface-management's start method.
  #
  # dlmgmtd gets the interface plumbed; this gets it an address. libipadm keeps
  # no address state of its own either -- `ipadm_create_addr()` goes out
  # through `ipadm_door_call()` to /etc/svc/volatile/ipadm/ipmgmt_door -- so
  # without this daemon `ifconfig <if> <addr>` fails with
  #
  #     ifconfig: could not create address:Object not found
  #
  # even though the `plumb` immediately before it succeeded. The two halves of
  # bringing up an interface fail separately and for different reasons; see
  # the header of nixpkgs' ipmgmtd.nix.
  ipScript = pkgs.writeScript "smf-ipmgmtd" ''
    #!${shell}
    # Generated by nixbsd for svc:/network/ip-interface-management.
    set -x

    # ipmgmtd rewrites ipadm.conf in place as addresses come and go, so the
    # seed copy from the package goes into the volatile tree rather than being
    # symlinked out of the store. /etc/ipadm is a symlink to that directory.
    ${pkgs.coreutils}/bin/mkdir -p ${volatile}/ipadm
    if [ ! -f ${volatile}/ipadm/ipadm.conf ]; then
      ${pkgs.coreutils}/bin/cp \
        ${ipmgmtd}/share/ipmgmtd/ipadm.conf \
        ${volatile}/ipadm/ipadm.conf
      ${pkgs.coreutils}/bin/chmod 644 ${volatile}/ipadm/ipadm.conf
    fi

    exec ${ipmgmtd}/lib/inet/ipmgmtd
  '';

  # svc:/network/physical's start method.
  #
  # Everything else ifconfig needs in order to succeed here was already in
  # place, and each piece of it was hard-won -- the `ddi-forceattach` in
  # kernel/drv/vioif.conf, without which the NIC is autodetached before
  # anything can open its DLPI node; the `solaris.*` authorisations in
  # /etc/user_attr, without which plumbing fails as "Insufficient user
  # authorizations" despite running as root; the `nss_files.so.1` in
  # /lib/amd64 that the uid-to-name lookup behind *that* check needs; and
  # /etc/netmasks. illumos-boot-image.nix documents each at length.
  #
  # What was missing was anything that ever *ran* it. `network/physical` was
  # one of the do-nothing milestone stubs below, so the interface was never
  # plumbed, and every service that binds a socket came online listening on a
  # host with no address -- which looks, from the outside, exactly like the
  # service having failed to start.
  #
  # Static, not DHCP: no dhcpagent is packaged, and qemu's user-mode network
  # hands out a fixed 10.0.2.0/24 with the guest at .15 regardless, so a lease
  # would only rediscover what is already known here. The runner's `hostfwd`
  # forwards to that address.
  netScript = pkgs.writeScript "smf-network-physical" ''
    #!${shell}
    # Generated by nixbsd for svc:/network/physical.
    #
    # Deliberately not `set -e`, and it ends in `exit 0`. A NIC that will not
    # plumb must not take this service into maintenance, because every other
    # milestone is ordered behind it and the whole graph would stall on a
    # machine that is otherwise perfectly usable. The trace below says what
    # actually happened; the exit status only says whether to keep going.
    set -x

    # lo0 is not decoration and not conditional. sshd binds the wildcard and
    # does not need it, but anything that connects to itself does, and
    # plumbing an already-plumbed lo0 is harmless.
    ${ifconfig}/sbin/ifconfig lo0 plumb 127.0.0.1 up

    ${optionalString (cfg.interface != null) ''
      # `plumb` and the address are two invocations, not one. A combined
      # `ifconfig <if> plumb <addr> up` works on an interface that is already
      # plumbed and fails on one that is not -- which is precisely the case
      # that occurs at boot, and the reason this is spelled out.
      ${ifconfig}/sbin/ifconfig ${cfg.interface} plumb
      ${ifconfig}/sbin/ifconfig ${cfg.interface} ${cfg.address} up
    ''}

    # Left in on purpose: this is the only record of what the interface list
    # looked like, and `svcs -L network/physical` is how it gets read back.
    ${ifconfig}/sbin/ifconfig -a
    exit 0
  '';
in
{
  options.boot.illumos.smf = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Bootstrap SMF at boot: configure sockets, create the writable
        repository under /etc/svc/volatile, import
        `system.build.smfManifests`, and start `svc.startd`.

        Off by default because it replaces the plain `svc.startd` line in
        /etc/inittab, and because a boot that reaches startd is still being
        brought up.
      '';
    };

    debugShell = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Run `illumos.init-shell` as /sbin/init instead of the real init, and
        leave the bootstrap script in the image to be run by hand.

        This exists because with real init there is *no* console prompt by
        design: /etc/inittab holds one `sysinit` line and nothing else, so a
        boot that reaches userland and a boot that hangs look identical on the
        console. With a shell as pid 1 the bootstrap's every step can be run
        and read individually, which is the only way to tell those two apart.
      '';
    };

    consoleDevice = mkOption {
      type = types.nullOr types.str;
      default = "/devices/pci@0,0/isa@1/asy@1,3f8:a";
      description = ''
        Device node the bootstrap script writes its output to, since
        /dev/console does not exist without devfsadm(8). The default is
        qemu's i440fx COM1 under the default `pci@0,0/isa@1` path. Set to
        null to leave the script's output on whatever init handed it.
      '';
    };

    interface = mkOption {
      type = types.nullOr types.str;
      default = "vioif0";
      description = ''
        Datalink for `svc:/network/physical` to plumb and address, or null to
        bring up loopback only.

        `vioif0` because the VM runner asks qemu for `virtio-net-pci`: the
        kernel carries `e1000g` too, but its attach(9E) unwinds silently after
        a `mac_register()` that can be seen to succeed.
      '';
    };

    address = mkOption {
      type = types.str;
      default = "10.0.2.15/24";
      description = ''
        Address for `boot.illumos.smf.interface`, in ifconfig(8)'s syntax.

        The default is the address qemu's user-mode network expects the guest
        to hold; the runner's `hostfwd` rule forwards to it.
      '';
    };

    sock2path = mkOption {
      type = types.lines;
      description = ''
        The soconfig(8) table, in the format of
        cmd/cmd-inet/etc/sock2path.d/: `family type protocol device-or-module`.

        Devices are named by their /devices path rather than /dev, because
        there is no devfsadm(8) to make the /dev links.
      '';
      default = ''
        # AF_UNIX. sockfs implements the socket layer, but the transport
        # underneath is TPI: family 1 maps onto minor nodes of drv/tl, the
        # transport loopback driver (uts/common/io/tl.c:524).
        1	2	0	/devices/pseudo/tl@0:ticotsord
        1	6	0	/devices/pseudo/tl@0:ticotsord
        1	1	0	/devices/pseudo/tl@0:ticlts

        # AF_INET / AF_INET6, by module name rather than device.
        2	2	0	tcp
        2	2	6	tcp
        26	2	0	tcp
        26	2	6	tcp
        2	1	0	udp
        2	1	17	udp
        26	1	0	udp
        26	1	17	udp
        2	4	0	icmp
        26	4	0	icmp

        # AF_ROUTE.
        24	4	0	rts
      '';
    };
  };

  config = mkIf (isIllumos && cfg.enable && available) {

    assertions = [
      {
        assertion = manifestDir != null;
        message = "boot.illumos.smf.enable needs system.build.smfManifests, i.e. init.backend = \"illumos\".";
      }
    ];

    # Replaces illumos-init.nix's plain `svc.startd` line. Everything the
    # bootstrap script does has to happen before startd, and there is nothing
    # else running that could do it.
    # The `co` line comes back, and it is the whole reason this is spelled out
    # rather than left as `smf::sysinit:` alone.
    #
    # illumos-init.nix writes both a `co::sysinit:/sbin/console-login` line and
    # an `smf::sysinit:` one; this `mkForce` used to replace the file wholesale
    # in order to put the bootstrap in startd's place, and silently took the
    # console away with it. The cost is not merely a missing prompt: startd
    # logs to /var/svc/log rather than to the console, so after `exec
    # svc.startd` the console goes permanently silent, and "startd brought
    # nine services online" and "startd wedged on its first door call" produce
    # byte-identical output -- which is to say, none. Every question about SMF
    # on this system was unanswerable from a normal boot.
    #
    # `co` first, deliberately: init runs `sysinit` entries in order and waits
    # for each, so the console exists before the bootstrap starts, and a
    # bootstrap that hangs still leaves a usable machine. See the long note in
    # illumos-init.nix for why console-login rather than a bare shell.
    boot.illumos.bootArchive.files."etc/inittab" = lib.mkForce (
      lib.optionalString (pkgs.illumos.console-login or null != null) ''
        co::sysinit:/sbin/console-login
      ''
      # Activation before the SMF bootstrap, for the same reason `co` comes
      # before both: init runs sysinit entries in order and waits for each, so
      # /etc exists before startd or any service reads it. See
      # `boot.illumos.activation` in illumos-boot-image.nix.
      + config.boot.illumos.activation.sysinitLine
      + ''
        smf::sysinit:${bootstrap}
      ''
    );

    boot.illumos.bootArchive.files."etc/sock2path.d/nixbsd" = cfg.sock2path;

    # Every generated manifest carries
    #
    #   <!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
    #
    # and svccfg parses with validation on, so a missing DTD is not a cosmetic
    # warning -- libxml2 reports "Could not load the external subset" and
    # svccfg answers "Document is not valid" and imports nothing at all. That
    # is a silent failure by the time startd sees it: the repository is merely
    # empty, which is indistinguishable from never having been populated.
    # `cmd/svc/dtd/service_bundle.dtd.1` in the gate is the file, installed to
    # this path by `cmd/svc/dtd/Makefile`.
    boot.illumos.bootArchive.files."usr/share/lib/xml/dtd/service_bundle.dtd.1" =
      builtins.readFile "${pkgs.illumos.source}/usr/src/cmd/svc/dtd/service_bundle.dtd.1";

    # `init.shellProgram` rather than forcing `extraFiles."sbin/init"` to
    # init-shell directly. The same wiring, with one difference that matters:
    # /sbin/init is computed from this now (see illumos-boot-image.nix), so
    # anything interposed in front of userland -- the virtio-fs store mount,
    # through `init.preExec` -- lands between init-shell and the shell, instead
    # of being discarded along with the option this used to overwrite.
    boot.illumos.init.shellProgram = lib.mkIf (
      cfg.debugShell && pkgs.illumos ? init-shell
    ) pkgs.bashInteractive;

    # The bootstrap is reachable by name from the debug shell, not only
    # through /etc/inittab.
    boot.illumos.bootArchive.symlinks."lib/svc/bin/smf-bootstrap" = "${bootstrap}";

    # `svc:/milestone/single-user:default` is not decoration. can_come_up()
    # (cmd/svc/startd/graph.c:3712) walks a fixed list -- single-user,
    # console-login, install-setup, install -- and returns false when none of
    # them is present or satisfiable. graph_thread() responds to a false
    # answer by spawning sulogin_thread (graph.c:6193), which forks
    # /sbin/sulogin on /dev/console in a loop; neither of those exists here,
    # so every boot without one of these four services turns into a retry
    # storm before anything else can run.
    #
    # The real milestone comes from the gate's milestone/single-user.xml,
    # which depends on a dozen services none of which are packaged. This is
    # the same thing reduced to its one load-bearing property: a service that
    # exists, is enabled and reaches `online` on its own.
    # The same reasoning applies to every *other* milestone a generated
    # manifest names. `portable/illumos.nix` maps the rc(8) dummy services onto
    # real FMRIs -- FILESYSTEMS onto svc:/system/filesystem/local, DAEMON and
    # LOGIN onto svc:/milestone/multi-user, and so on -- and SMF has no notion
    # of "order against this if it exists": a dependency on an FMRI that is
    # never delivered simply stays unsatisfied, and the service never comes
    # online. Observed with `svcs -xv` on a booted system:
    #
    #     svc:/site/sshd:default (Secure Shell Daemon)
    #      State: offline since ...
    #     Reason: Dependency svc:/milestone/multi-user is absent.
    #
    # and likewise filesystem/local for suid-sgid-wrappers and
    # filesystem/minimal for tempfiles. So deliver all of them, on the same
    # terms as single-user: a service that exists, is enabled, and reaches
    # `online` on its own.
    #
    # The orderings between them are upstream's (minimal before local,
    # single-user before multi-user), kept so that a service ordered against
    # one of these still lands on the right side of the others. They are one
    # FMRI each, so they do not trip the configd bug that `renderDependency`
    # works around.
    #
    # These are stand-ins. As the real services behind each milestone get
    # packaged -- mount, devfsadm, the network stack -- the corresponding stub
    # should be replaced by the genuine article rather than left to shadow it.
    smf.services =
      let
        milestone = commonName: after: {
          type = "milestone";
          duration = "transient";
          template.commonName = commonName;
          execMethods.start.exec = ":true";
          execMethods.stop.exec = ":true";
          dependencies = lib.optionalAttrs (after != null) {
            after = {
              grouping = "require_all";
              restartOn = "none";
              type = "service";
              fmris = [ after ];
            };
          };
        };
      in
      {
        "system/filesystem/minimal" = milestone "minimal filesystems" null;
        "system/filesystem/local" = milestone "local filesystems" "svc:/system/filesystem/minimal";
        "milestone/single-user" = milestone "single-user milestone" "svc:/system/filesystem/local";
        # Behind `milestone/network`, not `milestone/single-user`, and the chain
        # below puts single-user behind it in turn. sshd is ordered against
        # multi-user, and binding the wildcard address before the interface is
        # plumbed would leave a service that is `online` and unreachable --
        # the failure mode hardest to tell apart from a broken daemon.
        "milestone/multi-user" = milestone "multi-user milestone" "svc:/milestone/network";
        "system/identity" = milestone "system identity" null;
        # Not a milestone either: the daemon every datalink lookup goes
        # through. See `dlScript`. `contract`, because dlmgmtd forks and lets
        # its parent exit, so there is a process for startd to hold on to.
        "network/datalink-management" =
          lib.recursiveUpdate (milestone "datalink management" "svc:/milestone/single-user")
            {
              type = "service";
              duration = "contract";
              execMethods.start.exec = "${dlScript}";
            };

        # And the address half, for the same reason. See `ipScript`.
        "network/ip-interface-management" =
          lib.recursiveUpdate (milestone "IP interface management" "svc:/network/datalink-management")
            {
              type = "service";
              duration = "contract";
              execMethods.start.exec = "${ipScript}";
            };

        # The other entry that is no longer a stub: see `netScript`. Still
        # `transient` -- ifconfig configures the interface and exits, leaving
        # no process to supervise -- so it differs from its milestone
        # neighbours only in actually doing something.
        #
        # `recursiveUpdate` rather than `//`: the latter replaces the whole
        # `execMethods` attribute and would silently drop the stop method
        # along with it.
        "network/physical" =
          lib.recursiveUpdate (milestone "physical network interfaces" "svc:/network/ip-interface-management")
            {
              type = "service";
              execMethods.start.exec = "${netScript}";
            };
        "milestone/network" = milestone "network milestone" "svc:/network/physical";

        # Not a milestone, and not decoration either: this is what stops the
        # sulogin retry storm.
        #
        # can_come_up() (graph.c:3712) walks `up_svcs[]` -- single-user,
        # console-login, install-setup, install -- starting at index
        # `(booting_to_single_user ? 0 : 1)`. Since we do not boot to single
        # user, index 0 is skipped, so the `milestone/single-user` above can
        # *never* satisfy it however healthy it is, and console-login is the
        # first entry actually consulted. With none of the four present,
        # can_come_up() stays false and sulogin_thread (graph.c:3863) loops on
        # run_sulogin() forever, printing
        #
        #     Console login service(s) cannot run
        #     Requesting System Maintenance Mode
        #
        # That storm is not merely noisy: it burns the single CPU the guest
        # has, and the service graph crawls behind it -- milestones were
        # observed taking tens of seconds each to come online, in varying
        # order between boots.
        #
        # The console itself is still provided by /etc/inittab's
        # `co::sysinit:/sbin/console-login` line (see illumos-init.nix); this
        # service exists so that startd can see that a console login exists.
        # When console-login moves into SMF properly -- which is upstream's
        # arrangement, where inittab carries only the svc.startd line -- this
        # stub should become the real service rather than sit alongside it.
        "system/console-login" = milestone "console login" null;
      };

    # /var/run has to be a *symlink* into the writable tmpfs, not the empty
    # read-only directory the default mount-point list creates. The archive
    # builder makes the mount points before it makes the symlinks, and
    # `ln -sfn target dir` puts the link *inside* the directory rather than
    # replacing it, so the directory must not be created in the first place.
    boot.illumos.bootArchive.mountPoints = lib.mkForce [
      "dev"
      "devices"
      "proc"
      "tmp"
      "system/contract"
      "system/object"
      "system/boot"
      "etc/svc/volatile"
      "etc/dfs"
      "usr"
    ];

    boot.illumos.bootArchive.symlinks = {
      # Overrides illumos-init.nix's direct link; see configdWrapper above.
      "lib/svc/bin/svc.configd" = lib.mkForce "${configdWrapper}";

      # svccfg imports from here, and manifest-import would too.
      "lib/svc/manifest" = "${manifestDir}";

      # log_init() prefers /var/svc/log and falls back to /etc/svc/volatile
      # (cmd/svc/startd/log.c:671); give it the real path, pointed at the one
      # writable filesystem.
      "var/svc/log" = "${volatile}/svc-log";
      "var/run" = "${volatile}/var-run";
      "var/adm" = "${volatile}/var-adm";

      # Every method script generated by init/portable/illumos.nix ends its
      # command with `>>/var/log/<name>.log 2>&1` (`svc.defaultLog`). A shell
      # reports a failed *redirection* by failing the whole command, so with
      # no /var/log every method fails before its program is ever reached --
      # observed as `Method "... start" failed with exit status 10` for
      # nix-daemon and sysctl alike, which reads like a fault in the program
      # rather than in the directory it logs to.
      "var/log" = "${volatile}/var-log";

      # nix-daemon wants to create /nix/var/nix/{db,daemon-socket,...}.
      "nix/var" = "${volatile}/nix-var";

      # dlmgmtd rewrites datalink.conf as links come and go, so this has to be
      # a writable directory rather than a store path. `dlScript` seeds it
      # from the copy in the dlmgmtd package on first start.
      "etc/dladm" = "${volatile}/dladm";

      # Same again for ipmgmtd, which rewrites ipadm.conf in place.
      "etc/ipadm" = "${volatile}/ipadm";
    };

    # Reached only through the symlinks above and through the bootstrap
    # script, so nothing in `toplevel` refers to them.
    boot.illumos.bootArchive.storePaths = lib.mkDefault [
      bootstrap
      configdWrapper
      svccfg
      soconfig
      netScript
      dlScript
      ipScript
      manifestDir
    ];
  };
}
