{
  lib,
  config,
  pkgs,
  ...
}:

# What SMF needs at *runtime*, as opposed to what it needs to be packaged.
#
# ../boot/illumos-init.nix puts `svc.startd` in /etc/inittab and symlinks the
# two daemons into /lib/svc/bin. That is enough for init to try, and not
# nearly enough for startd to succeed, because three things it takes for
# granted are absent here:
#
#   * **A writable repository.** svc.configd opens `/etc/svc/repository.db`
#     (REPOSITORY_DB, lib/libscf/inc/libscf_priv.h:301) with a hard-coded
#     path, and startd exec's it with *no arguments at all*
#     (cmd/svc/startd/fork.c:485), so there is no knob to turn. The root is
#     read-only hsfs, and sqlite needs to write the database, its journal and
#     its temporaries. The one writable filesystem that exists this early is
#     /etc/svc/volatile, a tmpfs the *kernel* mounts in vfs_mountdevices()
#     (uts/common/fs/vfs.c:936) -- so `/lib/svc/bin/svc.configd` is pointed at
#     a wrapper that passes `-r` naming a repository over there. configd
#     already puts everything else (the door, the nonpersistent database, the
#     sqlite temp directory) in /etc/svc/volatile, so this makes the whole
#     repository live in one place.
#
#   * **A repository with something in it.** configd creates an empty, valid,
#     *serviceless* repository when the file is absent
#     (backend.c:1873 -> BACKEND_CREATE_NEED_INIT -> backend_init_schema), and
#     startd survives that -- libscf_populate_graph() over an empty scope is
#     zero iterations, not an error. But `can_come_up()` is then false, and
#     graph_thread() responds by spawning sulogin_thread (graph.c:6193), which
#     forks /sbin/sulogin on /dev/console forever. Neither exists. So the
#     repository has to be populated *before* startd starts, which is what
#     `svccfg import` under SVCCFG_REPOSITORY does below: that variable makes
#     svccfg fork a private svc.configd against a named database
#     (svccfg_engine.c:488), which is the only way to write a repository with
#     no restarter running.
#
#   * **Sockets.** sockfs keeps no built-in family/type/protocol table --
#     sockparams_init() (uts/common/fs/sockfs/sockparams.c:87) creates an
#     empty list -- so until soconfig(8) has issued the `sockconfig` syscall
#     every socket(2) returns EPROTONOSUPPORT, unix-domain included. On a real
#     system /lib/svc/method/devices-local runs `soconfig -d /etc/sock2path.d`;
#     here it has to happen before startd, because nothing is running that
#     could run a method yet.
#
# Everything is therefore funnelled through one script that init runs in
# startd's place: it makes the writable tree, configures sockets, imports the
# manifests and then exec's startd.

let
  inherit (lib)
    mkIf
    mkOption
    types
    optionalString
    ;

  isIllumos = config.nixpkgs.hostPlatform.isSunOS;
  cfg = config.boot.illumos.smf;

  startd = pkgs.illumos.svc-startd or null;
  configd = pkgs.illumos.svc-configd or null;
  svccfg = pkgs.illumos.svccfg or null;
  soconfig = pkgs.illumos.soconfig or null;

  # Spelled `or null` throughout, and gated on all four: this module has to
  # stay evaluable against a nixpkgs that has not packaged them yet. See the
  # same reasoning in illumos-init.nix.
  available = startd != null && configd != null && svccfg != null && soconfig != null;

  volatile = "/etc/svc/volatile";
  repository = "${volatile}/repository.db";

  manifestDir = config.system.build.smfManifests or null;

  shell = "${pkgs.bash}/bin/bash";

  # startd exec's CONFIGD_PATH with an empty argv (fork.c:485), so the only
  # place to add `-r` is the file that path names. A `#!` script works because
  # exec/intpexec is in the kernel's module list.
  configdWrapper = pkgs.writeScript "svc.configd-wrapper" ''
    #!${shell}
    exec ${configd}/lib/svc/bin/svc.configd -r ${repository} "$@"
  '';

  bootstrap = pkgs.writeScript "smf-bootstrap" ''
    #!${shell}
    # Generated by nixbsd. Runs as init's `sysinit` entry, in place of
    # svc.startd, and exec's svc.startd at the end.

    ${optionalString (cfg.consoleDevice != null) ''
      # There is no /dev/console: devfsadm(8) creates it and is not packaged.
      # Write to the device node instead, so that a failure here is visible
      # rather than silent. Deliberately not `set -e`: every step below is
      # best-effort, and losing the console must not stop the boot.
      #
      # Note there is no `</dev/null` here, and there must not be: /dev/null
      # does not exist either, and a shell reports a failed *redirection* by
      # failing the whole command, so adding it would silently cost the log.
      exec >>${cfg.consoleDevice} 2>&1 || :
    ''}
    set -x

    # init hands its children a minimal environment (see /etc/default/init,
    # which definit(3) reads for TZ and CMASK and nothing else), so name the
    # utilities' directory rather than trusting a default PATH.
    PATH=${pkgs.coreutils}/bin:${pkgs.bash}/bin
    export PATH

    # The writable tree. /etc/svc/volatile is a kernel-mounted tmpfs; each of
    # these is the target of a symlink baked into the read-only root.
    mkdir -p ${volatile}/svc-log ${volatile}/var-run ${volatile}/var-adm \
             ${volatile}/var-log ${volatile}/nix-var/nix ${volatile}/tmp
    chmod 1777 ${volatile}/tmp

    # Without this every socket(2) fails, whatever the family.
    ${soconfig}/bin/soconfig -d /etc/sock2path.d

    # A repository with no services in it makes startd go straight to
    # sulogin, so populate it here rather than leaving it to
    # manifest-import.
    #
    # SVCCFG_CONFIGD_PATH names the *real* binary rather than letting svccfg
    # fall back to /lib/svc/bin/svc.configd, which is the wrapper above:
    # svccfg passes its own `-r`, and going through the wrapper would mean two
    # of them on one command line.
    #
    # The files are named, rather than the directory: `smf.manifests` lays
    # them out by service name, so they sit one and two levels down
    # (site/nix-daemon.xml, milestone/single-user.xml), and svccfg's directory
    # walk is not recursive.
    if [ ! -f ${repository} ]; then
      shopt -s nullglob
      # Three levels, not two: FMRIs nest as deeply as their name does, so
      # `svc:/system/filesystem/local` lands at
      # manifest/system/filesystem/local.xml. A two-level glob silently misses
      # those, and the only symptom is the services that depend on them sitting
      # offline forever with "Dependency ... is absent".
      manifests=(
        /lib/svc/manifest/*.xml
        /lib/svc/manifest/*/*.xml
        /lib/svc/manifest/*/*/*.xml
      )
      SVCCFG_REPOSITORY=${repository} \
      SVCCFG_CONFIGD_PATH=${configd}/lib/svc/bin/svc.configd \
      SVCCFG_DOOR_PATH=${volatile} \
        ${svccfg}/bin/svccfg import "''${manifests[@]}"
    fi

    exec /lib/svc/bin/svc.startd
  '';
in
{
  options.boot.illumos.smf = {
    enable = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Bootstrap SMF at boot: configure sockets, create the writable
        repository under /etc/svc/volatile, import
        `system.build.smfManifests`, and start `svc.startd`.

        Off by default because it replaces the plain `svc.startd` line in
        /etc/inittab, and because a boot that reaches startd is still being
        brought up.
      '';
    };

    debugShell = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Run `illumos.init-shell` as /sbin/init instead of the real init, and
        leave the bootstrap script in the image to be run by hand.

        This exists because with real init there is *no* console prompt by
        design: /etc/inittab holds one `sysinit` line and nothing else, so a
        boot that reaches userland and a boot that hangs look identical on the
        console. With a shell as pid 1 the bootstrap's every step can be run
        and read individually, which is the only way to tell those two apart.
      '';
    };

    consoleDevice = mkOption {
      type = types.nullOr types.str;
      default = "/devices/pci@0,0/isa@1/asy@1,3f8:a";
      description = ''
        Device node the bootstrap script writes its output to, since
        /dev/console does not exist without devfsadm(8). The default is
        qemu's i440fx COM1 under the default `pci@0,0/isa@1` path. Set to
        null to leave the script's output on whatever init handed it.
      '';
    };

    sock2path = mkOption {
      type = types.lines;
      description = ''
        The soconfig(8) table, in the format of
        cmd/cmd-inet/etc/sock2path.d/: `family type protocol device-or-module`.

        Devices are named by their /devices path rather than /dev, because
        there is no devfsadm(8) to make the /dev links.
      '';
      default = ''
        # AF_UNIX. sockfs implements the socket layer, but the transport
        # underneath is TPI: family 1 maps onto minor nodes of drv/tl, the
        # transport loopback driver (uts/common/io/tl.c:524).
        1	2	0	/devices/pseudo/tl@0:ticotsord
        1	6	0	/devices/pseudo/tl@0:ticotsord
        1	1	0	/devices/pseudo/tl@0:ticlts

        # AF_INET / AF_INET6, by module name rather than device.
        2	2	0	tcp
        2	2	6	tcp
        26	2	0	tcp
        26	2	6	tcp
        2	1	0	udp
        2	1	17	udp
        26	1	0	udp
        26	1	17	udp
        2	4	0	icmp
        26	4	0	icmp

        # AF_ROUTE.
        24	4	0	rts
      '';
    };
  };

  config = mkIf (isIllumos && cfg.enable && available) {

    assertions = [
      {
        assertion = manifestDir != null;
        message = "boot.illumos.smf.enable needs system.build.smfManifests, i.e. init.backend = \"illumos\".";
      }
    ];

    # Replaces illumos-init.nix's plain `svc.startd` line. Everything the
    # bootstrap script does has to happen before startd, and there is nothing
    # else running that could do it.
    boot.illumos.bootArchive.files."etc/inittab" = lib.mkForce ''
      smf::sysinit:${bootstrap}
    '';

    boot.illumos.bootArchive.files."etc/sock2path.d/nixbsd" = cfg.sock2path;

    # Every generated manifest carries
    #
    #   <!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
    #
    # and svccfg parses with validation on, so a missing DTD is not a cosmetic
    # warning -- libxml2 reports "Could not load the external subset" and
    # svccfg answers "Document is not valid" and imports nothing at all. That
    # is a silent failure by the time startd sees it: the repository is merely
    # empty, which is indistinguishable from never having been populated.
    # `cmd/svc/dtd/service_bundle.dtd.1` in the gate is the file, installed to
    # this path by `cmd/svc/dtd/Makefile`.
    boot.illumos.bootArchive.files."usr/share/lib/xml/dtd/service_bundle.dtd.1" =
      builtins.readFile "${pkgs.illumos.source}/usr/src/cmd/svc/dtd/service_bundle.dtd.1";

    boot.illumos.bootArchive.extraFiles."sbin/init" =
      lib.mkIf (cfg.debugShell && pkgs.illumos ? init-shell)
        (lib.mkForce "${pkgs.illumos.init-shell}/sbin/init");

    # The bootstrap is reachable by name from the debug shell, not only
    # through /etc/inittab.
    boot.illumos.bootArchive.symlinks."lib/svc/bin/smf-bootstrap" = "${bootstrap}";

    # `svc:/milestone/single-user:default` is not decoration. can_come_up()
    # (cmd/svc/startd/graph.c:3712) walks a fixed list -- single-user,
    # console-login, install-setup, install -- and returns false when none of
    # them is present or satisfiable. graph_thread() responds to a false
    # answer by spawning sulogin_thread (graph.c:6193), which forks
    # /sbin/sulogin on /dev/console in a loop; neither of those exists here,
    # so every boot without one of these four services turns into a retry
    # storm before anything else can run.
    #
    # The real milestone comes from the gate's milestone/single-user.xml,
    # which depends on a dozen services none of which are packaged. This is
    # the same thing reduced to its one load-bearing property: a service that
    # exists, is enabled and reaches `online` on its own.
    # The same reasoning applies to every *other* milestone a generated
    # manifest names. `portable/illumos.nix` maps the rc(8) dummy services onto
    # real FMRIs -- FILESYSTEMS onto svc:/system/filesystem/local, DAEMON and
    # LOGIN onto svc:/milestone/multi-user, and so on -- and SMF has no notion
    # of "order against this if it exists": a dependency on an FMRI that is
    # never delivered simply stays unsatisfied, and the service never comes
    # online. Observed with `svcs -xv` on a booted system:
    #
    #     svc:/site/sshd:default (Secure Shell Daemon)
    #      State: offline since ...
    #     Reason: Dependency svc:/milestone/multi-user is absent.
    #
    # and likewise filesystem/local for suid-sgid-wrappers and
    # filesystem/minimal for tempfiles. So deliver all of them, on the same
    # terms as single-user: a service that exists, is enabled, and reaches
    # `online` on its own.
    #
    # The orderings between them are upstream's (minimal before local,
    # single-user before multi-user), kept so that a service ordered against
    # one of these still lands on the right side of the others. They are one
    # FMRI each, so they do not trip the configd bug that `renderDependency`
    # works around.
    #
    # These are stand-ins. As the real services behind each milestone get
    # packaged -- mount, devfsadm, the network stack -- the corresponding stub
    # should be replaced by the genuine article rather than left to shadow it.
    smf.services =
      let
        milestone = commonName: after: {
          type = "milestone";
          duration = "transient";
          template.commonName = commonName;
          execMethods.start.exec = ":true";
          execMethods.stop.exec = ":true";
          dependencies = lib.optionalAttrs (after != null) {
            after = {
              grouping = "require_all";
              restartOn = "none";
              type = "service";
              fmris = [ after ];
            };
          };
        };
      in
      {
        "system/filesystem/minimal" = milestone "minimal filesystems" null;
        "system/filesystem/local" = milestone "local filesystems" "svc:/system/filesystem/minimal";
        "milestone/single-user" = milestone "single-user milestone" "svc:/system/filesystem/local";
        "milestone/multi-user" = milestone "multi-user milestone" "svc:/milestone/single-user";
        "system/identity" = milestone "system identity" null;
        "network/physical" = milestone "physical network interfaces" null;
        "milestone/network" = milestone "network milestone" "svc:/network/physical";

        # Not a milestone, and not decoration either: this is what stops the
        # sulogin retry storm.
        #
        # can_come_up() (graph.c:3712) walks `up_svcs[]` -- single-user,
        # console-login, install-setup, install -- starting at index
        # `(booting_to_single_user ? 0 : 1)`. Since we do not boot to single
        # user, index 0 is skipped, so the `milestone/single-user` above can
        # *never* satisfy it however healthy it is, and console-login is the
        # first entry actually consulted. With none of the four present,
        # can_come_up() stays false and sulogin_thread (graph.c:3863) loops on
        # run_sulogin() forever, printing
        #
        #     Console login service(s) cannot run
        #     Requesting System Maintenance Mode
        #
        # That storm is not merely noisy: it burns the single CPU the guest
        # has, and the service graph crawls behind it -- milestones were
        # observed taking tens of seconds each to come online, in varying
        # order between boots.
        #
        # The console itself is still provided by /etc/inittab's
        # `co::sysinit:/sbin/console-login` line (see illumos-init.nix); this
        # service exists so that startd can see that a console login exists.
        # When console-login moves into SMF properly -- which is upstream's
        # arrangement, where inittab carries only the svc.startd line -- this
        # stub should become the real service rather than sit alongside it.
        "system/console-login" = milestone "console login" null;
      };

    # /var/run has to be a *symlink* into the writable tmpfs, not the empty
    # read-only directory the default mount-point list creates. The archive
    # builder makes the mount points before it makes the symlinks, and
    # `ln -sfn target dir` puts the link *inside* the directory rather than
    # replacing it, so the directory must not be created in the first place.
    boot.illumos.bootArchive.mountPoints = lib.mkForce [
      "dev"
      "devices"
      "proc"
      "tmp"
      "system/contract"
      "system/object"
      "system/boot"
      "etc/svc/volatile"
      "etc/dfs"
      "usr"
    ];

    boot.illumos.bootArchive.symlinks = {
      # Overrides illumos-init.nix's direct link; see configdWrapper above.
      "lib/svc/bin/svc.configd" = lib.mkForce "${configdWrapper}";

      # svccfg imports from here, and manifest-import would too.
      "lib/svc/manifest" = "${manifestDir}";

      # log_init() prefers /var/svc/log and falls back to /etc/svc/volatile
      # (cmd/svc/startd/log.c:671); give it the real path, pointed at the one
      # writable filesystem.
      "var/svc/log" = "${volatile}/svc-log";
      "var/run" = "${volatile}/var-run";
      "var/adm" = "${volatile}/var-adm";

      # Every method script generated by init/portable/illumos.nix ends its
      # command with `>>/var/log/<name>.log 2>&1` (`svc.defaultLog`). A shell
      # reports a failed *redirection* by failing the whole command, so with
      # no /var/log every method fails before its program is ever reached --
      # observed as `Method "... start" failed with exit status 10` for
      # nix-daemon and sysctl alike, which reads like a fault in the program
      # rather than in the directory it logs to.
      "var/log" = "${volatile}/var-log";

      # nix-daemon wants to create /nix/var/nix/{db,daemon-socket,...}.
      "nix/var" = "${volatile}/nix-var";
    };

    # Reached only through the symlinks above and through the bootstrap
    # script, so nothing in `toplevel` refers to them.
    boot.illumos.bootArchive.storePaths = lib.mkDefault [
      bootstrap
      configdWrapper
      svccfg
      soconfig
      manifestDir
    ];
  };
}
