{
  config,
  pkgs,
  lib,
  ...
}:

with lib;
let
  cfg = config.illumos.rc;

  services = config.init.services;

  # `init.services` names map onto SMF service names under `site/`, the
  # namespace reserved for services not delivered by the OS itself.
  smfName = name: "site/${name}";
  fmriOf = name: "svc:/${smfName name}:default";

  # Most `init.services` ordering constraints in nixbsd are written against the
  # BSD rc(8) "dummy" services -- FILESYSTEMS, LOGIN, DAEMON and friends --
  # which have no counterpart in `init.services` itself. SMF expresses the same
  # idea with milestones, so translate the ones that have an obvious
  # equivalent rather than dropping them.
  milestones = {
    # rc(8) orders mountcritlocal < FILESYSTEMS, so these must not collapse
    # onto the same milestone or a service that is after one and before the
    # other becomes a dependency cycle.
    mountcritlocal = "svc:/system/filesystem/minimal";
    FILESYSTEMS = "svc:/system/filesystem/local";
    mount-final = "svc:/system/filesystem/local";
    NETWORKING = "svc:/milestone/network";
    netif = "svc:/network/physical";
    netwait = "svc:/milestone/network";
    SERVERS = "svc:/milestone/single-user";
    DAEMON = "svc:/milestone/multi-user";
    LOGIN = "svc:/milestone/multi-user";
    sysctl = "svc:/system/identity";
  };

  # SMF has no notion of "order against this if it exists"; a dependency on an
  # FMRI that is never delivered simply stays unsatisfied and the service never
  # comes online. So resolve to a real FMRI or drop the edge entirely.
  # A dependent's name becomes a property group name in the *target* service,
  # where "/" and ":" are not allowed.
  fmriToIdent = fmri: replaceStrings [ "svc:/" "/" ":" ] [ "" "-" "-" ] fmri;

  resolve =
    names:
    filter (f: f != null) (
      map (d: if services ? ${d} then fmriOf d else milestones.${d} or null) names
    );

  duration =
    svc:
    {
      # The command stays in the foreground and *is* the daemon.
      foreground = "child";
      # The command forks and exits; the daemon lives on in the contract.
      forking = "contract";
      # The command runs to completion.
      oneshot = "transient";
    }
    .${svc.startType};

  # One method script per service, in the shape of illumos' own
  # /lib/svc/method/* scripts: `<script> start|stop`. Putting the environment,
  # working directory, pre/post hooks and logging here rather than in the
  # manifest keeps the XML close to what a hand-written illumos manifest looks
  # like, and gives the placeholder rc script below something to call.
  methodScript =
    name: svc:
    let
      cmd = concatMapStringsSep " " (x: escapeShellArg (toString x)) svc.startCommand;
      env = concatStrings (
        mapAttrsToList (n: v: "export ${n}=${escapeShellArg v}\n") (
          config.init.environment // svc.environment
        )
      );
      path = optionalString (svc.path != [ ]) "export PATH=${makeBinPath svc.path}\${PATH:+:$PATH}\n";
      redir = optionalString svc.defaultLog.enable " >>/var/log/${svc.defaultLog.name}.log 2>&1";
    in
    pkgs.writeScript "smf-method-${name}" ''
      #!${cfg.shell}
      # Generated by nixbsd for svc:/${smfName name}.
      set -u
      ${env}${path}${optionalString (svc.environmentFile != null) ". ${svc.environmentFile}"}
      case "''${1:-start}" in
      start)
        ${optionalString (svc.directory != null) "cd ${escapeShellArg svc.directory}"}
        ${optionalString (svc.preStart != null) svc.preStart}
        ${cmd}${redir}
        ${optionalString (svc.postStart != null) svc.postStart}
        ;;
      stop)
        ${optionalString (svc.preStop != null) svc.preStop}
        ${
          if svc.stopCommand != null then
            svc.stopCommand
          else if svc.pidFile != null then
            "kill -${svc.stopSignal} \"$(cat ${escapeShellArg svc.pidFile})\""
          else
            # Only reachable when preStop/postStop are set but no stopCommand
            # is: the actual killing is svc.startd's job (see `:kill` below).
            ":"
        }
        ${optionalString (svc.postStop != null) svc.postStop}
        ;;
      *)
        echo "usage: $0 start|stop" >&2
        exit 2
        ;;
      esac
    '';

  methodScripts = mapAttrs methodScript services;

  convertService = name: svc: {
    duration = duration svc;

    template.commonName = if svc.description != "" then svc.description else name;

    methodContext = {
      user = mkIf (svc.user != "root") svc.user;
      workingDirectory = mkIf (svc.directory != null) svc.directory;
    };

    execMethods.start = {
      exec = "${methodScripts.${name}} start";
      # `init.services` has no timeout concept; oneshot commands are expected
      # to be quick, daemons may take a while to settle.
      timeoutSeconds = if svc.startType == "oneshot" then 60 else 0;
    };

    execMethods.stop =
      if svc.stopCommand == null && svc.preStop == null && svc.postStop == null then
        {
          # svc.startd's built-in "signal every member of the contract" method.
          exec = ":kill";
          timeoutSeconds = 60;
        }
      else
        {
          exec = "${methodScripts.${name}} stop";
          timeoutSeconds = 60;
        };

    dependencies = optionalAttrs (resolve svc.dependencies != [ ]) {
      # One dependency element rather than one per FMRI: `require_all` over the
      # whole set says exactly what `init.services.<name>.dependencies` means.
      after = {
        grouping = "require_all";
        restartOn = "none";
        type = "service";
        fmris = resolve svc.dependencies;
      };
    };

    dependents = listToAttrs (
      map
        (
          fmri:
          nameValuePair "${name}-before-${fmriToIdent fmri}" {
            grouping = "optional_all";
            restartOn = "none";
            fmris = [ fmri ];
          }
        )
        # Guard against `dependencies` and `before` resolving to the same FMRI,
        # which svc.startd would see as a cycle. Being ordered after something
        # wins over the weaker `before` hint.
        (subtractLists (resolve svc.dependencies) (resolve svc.before))
    );
  };

  # PLACEHOLDER runner ------------------------------------------------------
  #
  # Everything above is the real, declarative output. Since svc.startd,
  # svc.configd and libscf are not packaged (usr/src/cmd/svc/*), nothing on the
  # system can read a manifest yet, so we additionally emit a flat rc script
  # that invokes the *same* method scripts in dependency order. When SMF is
  # ported this script goes away and the manifests are unchanged.

  # Effective dependency edges: `before` on A adds an edge A -> B for each B.
  depsOf =
    name:
    let
      self = services.${name};
      fromBefore = concatLists (mapAttrsToList (other: o: optional (elem name o.before) other) services);
    in
    unique (filter (d: services ? ${d}) (self.dependencies ++ fromBefore));

  sorted =
    let
      result = toposort (a: b: elem a (depsOf b)) (attrNames services);
    in
    if result ? cycle then
      throw "Cycle in illumos init services: ${concatStringsSep " " result.cycle}"
    else
      result.result;

  mkService = name: svc: ''
    echo "starting ${smfName name}"
    ${methodScripts.${name}} start ${optionalString (svc.startType == "foreground") "&"}
  '';

  rcScript = pkgs.writeScript "illumos-rc" ''
    #!${cfg.shell}
    # Generated by nixbsd. PLACEHOLDER: illumos starts services via SMF
    # (svc.startd reading the manifests in `system.build.smfManifests`). Until
    # svc.startd is packaged this script runs each service's SMF start method
    # once, in dependency order. No supervision, no restart, no shutdown.
    set -u
    ${concatStringsSep "\n" (map (n: mkService n services.${n}) sorted)}
  '';
in
{
  options.illumos.rc = {
    shell = mkOption {
      type = types.str;
      default = "${pkgs.bash}/bin/bash";
      defaultText = literalExpression ''"''${pkgs.bash}/bin/bash"'';
      description = "Shell used to interpret the generated method and rc scripts.";
    };

    script = mkOption {
      type = types.package;
      readOnly = true;
      description = ''
        PLACEHOLDER rc script standing in for svc.startd. Runs every
        `init.services` entry's SMF start method once, in dependency order, at
        boot. No supervision, no restart, no shutdown handling.
      '';
    };
  };

  config = mkMerge [
    { init.backend = mkOptionDefault "illumos"; }
    (mkIf (config.init.backend == "illumos") {
      smf.services = mapAttrs' (
        name: svc: nameValuePair (smfName name) (convertService name svc)
      ) services;

      illumos.rc.script = rcScript;
      system.build.rcScript = rcScript;
    })
  ];
}
