{
  config,
  pkgs,
  lib,
  ...
}:

with lib;
let
  cfg = config.illumos.rc;

  # Topologically order services by `dependencies`/`before`. illumos proper uses
  # SMF (svc.startd + service manifests), which we do not implement; see the
  # PLACEHOLDER note on `illumos.rc.script` below.
  services = config.init.services;

  # Effective dependency edges: `before` on A adds an edge A -> B for each B.
  depsOf =
    name:
    let
      self = services.${name};
      fromBefore = concatLists (mapAttrsToList (other: o: optional (elem name o.before) other) services);
    in
    unique (filter (d: services ? ${d}) (self.dependencies ++ fromBefore));

  sorted =
    let
      result = toposort (a: b: elem a (depsOf b)) (attrNames services);
    in
    if result ? cycle then
      throw "Cycle in illumos init services: ${concatStringsSep " " result.cycle}"
    else
      result.result;

  mkEnv =
    svc:
    concatStringsSep "" (
      mapAttrsToList (n: v: "export ${n}=${escapeShellArg v}\n") (
        config.init.environment // svc.environment
      )
    );

  mkPath =
    svc:
    optionalString (
      svc.path != [ ] || config.init.environment ? PATH
    ) "export PATH=${makeBinPath svc.path}\${PATH:+:$PATH}\n";

  startLine =
    svc:
    let
      cmd = concatStringsSep " " (map (x: escapeShellArg (toString x)) svc.startCommand);
      redir = optionalString svc.defaultLog.enable " >>/var/log/${svc.defaultLog.name}.log 2>&1";
    in
    if svc.startType == "foreground" then "${cmd}${redir} &\n" else "${cmd}${redir}\n";

  mkService = name: svc: ''
    echo "starting ${name}"
    (
    ${optionalString (svc.directory != null) "cd ${escapeShellArg svc.directory}"}
    ${mkEnv svc}${mkPath svc}${optionalString (svc.environmentFile != null) ". ${svc.environmentFile}"}
    ${optionalString (svc.preStart != null) svc.preStart}
    ${startLine svc}
    ${optionalString (svc.postStart != null) svc.postStart}
    ) || echo "service ${name} failed"
  '';

  rcScript = pkgs.writeScript "illumos-rc" ''
    #!${cfg.shell}
    # Generated by nixbsd. PLACEHOLDER: illumos normally starts services via SMF
    # (svc.startd reading service manifests). This is a flat, sequential rc
    # script sufficient for early bring-up ("kernel boots, runs init") and is
    # NOT a replacement for SMF.
    set -u
    ${concatStringsSep "\n" (map (n: mkService n services.${n}) sorted)}
  '';
in
{
  options.illumos.rc = {
    shell = mkOption {
      type = types.str;
      default = "${pkgs.bash}/bin/bash";
      defaultText = literalExpression ''"''${pkgs.bash}/bin/bash"'';
      description = "Shell used to interpret the generated rc script.";
    };

    script = mkOption {
      type = types.package;
      readOnly = true;
      description = ''
        PLACEHOLDER rc script standing in for SMF. Runs every `init.services`
        entry once, in dependency order, at boot. No supervision, no restart,
        no shutdown handling.
      '';
    };
  };

  config = mkMerge [
    { init.backend = mkOptionDefault "illumos"; }
    (mkIf (config.init.backend == "illumos") {
      illumos.rc.script = rcScript;
      system.build.rcScript = rcScript;
    })
  ];
}
